# Generated by Django 2.2.19 on 2023-03-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('periods', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
